######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 23 23:32:17 2011
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = testziphandler
DEPENDPATH += . ../.. ../../minizip
INCLUDEPATH += . ../.. ../../minizip

# Input
HEADERS += ziphandler.h \
           unzip.h \
           ioapi.h
SOURCES += testziphandler.cpp \
           ziphandler.cpp \  
           unzip.c \
           ioapi.c
