######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 23 23:32:17 2011
######################################################################

QT += xml
CONFIG += qtestlib
TEMPLATE = app
TARGET = test
DEPENDPATH += . ../.. ../../minizip
INCLUDEPATH += . ../.. ../../minizip

# Input
HEADERS += ziphandler.h \
           epub.h \ 
           unzip.h \
           ioapi.h \
           opfhandler.h \
           ncxhandler.h
SOURCES += testepub.cpp \ 
           ziphandler.cpp \  
           epub.cpp \ 
           unzip.c \
           ioapi.c \ 
           opfhandler.cpp \ 
           ncxhandler.cpp
